# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ejimenez
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: calculator
service: arithmetic-calculator

provider:
  name: aws
  stage: ${env:stage, 'dev'}
  runtime: provided.al2023
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'rds:*' # Should use least-privileged access
          Resource:
            - arn:aws:rds:${aws:region}:${aws:accountId}:db:*

package:
  patterns:
    - '!./**/*'
    - ./bin/**/*

resources:
  Resources:
    CalcDatabase:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: calc
        DBInstanceClass: db.t4g.micro
        Engine: aurora-postgresql
        EngineVersion: '16.3'
        MasterUsername: postgres
        MasterUserPassword: Sup3rP4ssw0rd

functions:
  login:
    handler: bin/handlers/login
    events:
      - httpApi: POST /v1/login

  create_operation:
    handler: bin/handlers/create_operation/bootstrap
    events:
      - httpApi: POST /v1/operations

  fetch_records:
    handler: bin/handlers/fetch_records/bootstrap
    events:
      - httpApi: GET /v1/records

  delete_operations:
    handler: bin/handlers/delete_record/bootstrap
    events:
      - httpApi: DELETE /v1/records/{record_id}

  perform_operation:
    handler: bin/handlers/perform_operation/bootstrap
    events:
      - httpApi: POST /v1/operations/{operation_id}/perform
